### PR TITLE
Add support for Kibana 5.5.0

### PR DESCRIPTION
**Pull request by fbaligand**

### CODE REVIEW

**Comment by fbaligand** [comment]
Hi @amannocci

I have added support for Kibana 5.5.0. I made tests to check it works fine.
Could you review this PR ?

**Comment by amannocci** [comment]
Hi @fbaligand,

Thanks for your contribution.
I will review this PR as soon as possible.

**Comment by fbaligand** [comment]
Nice !

**Comment by fbaligand** [comment]
Thanks for the merge and the release !

**Pull request merged**
